### ISSUE TITLE
requesting touch event unbinding

### ISSUE THREAD

**Issue by UnsungHero97** [visiongeist/toe.js#11]
It seems like there's no way to remove the event handlers added by toe.js, except by doing it manually. I can do...

```
$(document).on('tap', '.button', function() {...});
```

... but I can't do...

```
$('.button').off('tap', function() {...});
```

Currently, it seems like the only way to unbind the 'tap' event is to manually unbind 'touchstart', 'touchend', 'touchcancel', and 'touchmove' on the element. It would be really nice if toe.js allowed for the unbinding of these events.

**Comment by visiongeist** [comment]
should be fixed by version 3.0. If not please reopen :)

**Comment by UnsungHero97** [comment]
I updated to v3.0, and I'm still seeing this problem. Here is a fiddle to demo my problem:

http://jsfiddle.net/UnsungHero97/yW6Lq/4/

Note that in the demo, I'm using toe.js, so you'll have to change your user-agent to be that of a mobile device for the "tap" events to fire... or actually use a mobile device.

Now, when I "tap" a blue button, the corresponding (sibling) magenta button should not be "tap"-able any more. Similarly, when I "tap" a magenta button, the corresponding (sibling) blue button should not be "tap"-able any more.

The reason I'm doing...

```
$(document).on('tap', '.blue', function() {...});
```

... is because these kinds of buttons can be dynamically inserted later on.

Does v3.0 support what I'm trying to do? If so, what would I have to change?

**Comment by visiongeist** [comment]
please check out this line: $(this).siblings()
you click on the button so this === button. you disable a non existing Event. Please use event.currentTarget
